void PreRun(void);
void SetupHardware(void);
int System_Timer();
char *Time(ulong *);
char *TimeDate(ulong *);
void Make_Directory(char *);
void DOS_Com(char *, long, char *, char *);
float Check_Timers(ushort);
bool Append_Files(int, const char *, bool, long);
long Free_Disk_Space();
void VEEStoreShort(char *, short);
void Sleep();
void CTDSleep();
void GetSettings();
short Check_Vitals();
void print_clock_cycle_count(clock_t, clock_t, char *);
