#!/bin/sh
# WISPR control script.
#

/bin/ifconfig eth0 192.168.0.20
# Uncomment these to cut cpu freq in half
echo userspace > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
echo 250000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_setspeed

cp /mnt/wispr_bw /bin
cp /mnt/spectrogram8kHz /bin/spectrogram
chmod 777 /bin/wispr_bw
chmod 777 /bin/spectrogram

echo " "
echo "--- Embedded Ocean Systems WISPR V1.0 ---"
echo -n "<hello />" > /dev/ttyBF1

while
  echo -n "<wispr>" > /dev/ttyBF1
  line=""
  # -s noecho -t timeout
  read -s -t 9 line < /dev/ttyBF1
do
  if [ -n "$line" ]; then
    echo -n "<ok />" > /dev/ttyBF1
    echo "$line"
    eval "$line"
    sync
    # clear cache to free memory ??
    echo 3 > /proc/sys/vm/drop_caches
    if mount | grep -qv /mnt; then
      # not mounted?
      echo mount /dev/sda1 /mnt
      mount /dev/sda1 /mnt
    fi
    echo -n "</wispr>" > /dev/ttyBF1
  fi
done

echo
echo done
echo -n "<exit />" > /dev/ttyBF1
if mount | grep -q /mnt; then
  echo umount /mnt
  umount /mnt
fi
