#!/bin/sh
# WISPR control script.
#

/bin/ifconfig eth0 192.168.0.20
# Uncomment these to cut cpu freq in half
echo userspace > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
echo 250000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_setspeed
# clear cache to free memory ??
# echo 3 > /proc/sys/vm/drop_caches

cp /mnt/wispr_bw /bin
cp /mnt/spectrogram8kHz /bin/spectrogram
chmod 777 /bin/wispr_bw
chmod 777 /bin/spectrogram

secs=3
com1=/dev/ttyBF1
# do commands from com1 until $secs second timeout

cd /mnt
echo " "
echo "--- Embedded Ocean Systems WISPR V1.0 --- ($secs sec to shell)"
echo -n "<wispr>" > $com1
echo "<wispr>"

while true; do
  line=""
  sleep 1
  echo -n "<cmd>" > $com1
  echo "<cmd>"
  # -s noecho -t timeout
  read -s -t $secs line < $com1
  if [ -n "$line" ]; then
    echo "$line"
    eval "$line"
  fi
  # if output created, write it up
  if [ -f /mnt/output ]; then
    wc /mnt/output
    cat /mnt/output > $com1
    rm /mnt/output
  fi
  sleep 1
  echo -n "</cmd>" > $com1
  echo "</cmd>"
  if [ -z "$line" ]; then break; fi
done

# cannot have too many files in top of msdos filesystem
if ls /mnt/*.flac 2>/dev/null; then
  mv /mnt/*.flac /mnt/flac
fi
if ls /mnt/*.log 2>/dev/null; then
  mv /mnt/*.log /mnt/log
fi


if mount | grep -q /mnt; then
  echo umounting /mnt ...
  cd /
  sync
  umount /mnt
  echo "try     mount /dev/sda1 /mnt"
fi
sleep 1
echo -n "</wispr>" > $com1
echo "</wispr>"
