#!/bin/sh
# WISPR control script.
#

/bin/ifconfig eth0 192.168.0.20
# Uncomment these to cut cpu freq in half
echo userspace > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
echo 250000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_setspeed
# clear cache to free memory ??
# echo 3 > /proc/sys/vm/drop_caches

cp /mnt/wispr_bw /bin
cp /mnt/spectrogram8kHz /bin/spectrogram
chmod 777 /bin/wispr_bw
chmod 777 /bin/spectrogram

# do commands from com1 until 10 second timeout

echo " "
echo "--- Embedded Ocean Systems WISPR V1.0 --- (10 sec to shell)"
date

while true; do
  line=""
  echo -n "<wispr>" > /dev/ttyBF1
  # -s noecho -t timeout
  read -s -t 10 line < /dev/ttyBF1
  if [ -z "$line" ]; then break; fi
  echo "$line"
  eval "$line"
  echo -n "</wispr>" > /dev/ttyBF1
done

if ls /mnt/*.flac; then mv /mnt/*.flac /mnt/flac; fi
if ls /mnt/*.log; then mv /mnt/*.log /mnt/log; fi


if mount | grep /mnt; then
  echo umounting /mnt ...
  sync
  umount /mnt
fi
echo "try     mount /dev/sda1 /mnt"
